// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_mdVIBDzsNHVBRWRKbwRoYbqwvB7xZns',
    appId: '1:950605628604:web:e9200a042ab87408d4bcb9',
    messagingSenderId: '950605628604',
    projectId: 'crypto-list-app-777',
    authDomain: 'crypto-list-app-777.firebaseapp.com',
    storageBucket: 'crypto-list-app-777.firebasestorage.app',
    measurementId: 'G-MS3ERF3Z40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHjET5CK-BUuznQkXvtZko6IbzfNoUw_g',
    appId: '1:950605628604:android:2021f12378b99ba7d4bcb9',
    messagingSenderId: '950605628604',
    projectId: 'crypto-list-app-777',
    storageBucket: 'crypto-list-app-777.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5bs7kLO_fACJzSo_wgAZSc462ZqHUJu4',
    appId: '1:950605628604:ios:ce0bcbd66bb2d1dad4bcb9',
    messagingSenderId: '950605628604',
    projectId: 'crypto-list-app-777',
    storageBucket: 'crypto-list-app-777.firebasestorage.app',
    iosBundleId: 'com.cryptoguys.cryptoCoinsList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5bs7kLO_fACJzSo_wgAZSc462ZqHUJu4',
    appId: '1:950605628604:ios:ce0bcbd66bb2d1dad4bcb9',
    messagingSenderId: '950605628604',
    projectId: 'crypto-list-app-777',
    storageBucket: 'crypto-list-app-777.firebasestorage.app',
    iosBundleId: 'com.cryptoguys.cryptoCoinsList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_mdVIBDzsNHVBRWRKbwRoYbqwvB7xZns',
    appId: '1:950605628604:web:007e9fa408ed0449d4bcb9',
    messagingSenderId: '950605628604',
    projectId: 'crypto-list-app-777',
    authDomain: 'crypto-list-app-777.firebaseapp.com',
    storageBucket: 'crypto-list-app-777.firebasestorage.app',
    measurementId: 'G-C9F992LWD6',
  );
}
